[package]
name = "poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
preserves = "3.990.0"
preserves-schema = "3.990.0"
ureq = "2.8.0"
